### ISSUE TITLE
Some functions are absent

### ISSUE THREAD

**Issue by Mokoghost** [cmacdow/fpCNMF#1]
I am applying your project to my dataset, but some functions seem to be lacking. I have implemented `isEven` in `Utilities/ProcessAndSplitData.m`. But I don't know what's the detail and function of `GrabFiles` in `Clustering/TemporalXCorrTensor_BigData.m` which is also lacking.

Can you guys upload this function? Your work is really awesome and helpful.

**Comment by cmacdow** [comment]
Hi Mokoghost. Yep. There are some general helpful functions that we use for a variety of repos and so they aren't included here. I've uploaded grabfiles and some others to the GenUtils repo.

**Comment by Mokoghost** [comment]
Thank you! Very helpful.
